name: 01-Building-blocks.yaml
on: push 
jobs:
   echo-hello:
         runs-on: self-hosted
         steps:
            - name: saying hello
              run: echo "hello  world"
   echo-goodbye:
          runs-on: self-hosted
          steps:
            - name: Achieved success
              run: |
                echo "I will succeeed "
                exit 0
            - name: saying good bye
              run: echo "Saying good bye"

              
