name: 02-workflow-events
on: 
 push:
 pull_request:
 workflow_dispatch:


jobs:
   echo:
      runs-on: self-hosted
      steps:
          - name: show the trigger
            run: echo "I am trigerred by an ${{github.event_name}}"





