name: 03-workflow-runner
on: 
  push:
jobs:
   workflow-runner: 
            runs-on: self-hosted
            steps:
             - name: show runners
               run: echo "I am running "$OS_RUNNER" runner"
            
       
