name: 04- using-actions
on: push
jobs:
 build:
   runs-on: self-hosted
     1.Install the dpendencies
     2.EXecute automated tests
   steps:
      - name: checkout repositories
        uses: actions/checkout@v4
      # - name: priniting folders
      #   run: ls
      - name: setup node
        uses: actions/setup-node@v3
        with: 
         node-version: '20.x'
      - name: Install dependencies
        run: npm ci

        
      


       


