name: 04- using-actions
on: push
jobs:
 build:
   runs-on: latest
     1.INstall the dpendencies
     2.EXecute automated tests
   steps:
      - name: checkout repositories
        run: actions/checkout@v4
      - name: priniting folders
        run: ls
